[package]
name = "sexp"
version = "0.1.0"
edition = "2021"
description = "S-Expressions for Rust"
[lib]
path = "lib.rs"
[[test]]
name = "tests"
path = "tests.rs"
[dependencies]
serde = "1.0.16"
[dev-dependencies]
serde_derive = "1.0.16"